# Generated by Django 3.1.7 on 2021-04-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='average_score',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='average score'),
        ),
        migrations.AddField(
            model_name='user',
            name='pronounced',
            field=models.PositiveBigIntegerField(default=0, verbose_name='total pronounced'),
        ),
    ]
