# Generated by Django 3.1.7 on 2021-04-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('word', models.CharField(db_index=True, max_length=128, primary_key=True, serialize=False, unique=True)),
                ('transcription', models.CharField(max_length=128)),
                ('audio_path', models.FilePathField(default=None, max_length=512, path='static/words_records')),
            ],
        ),
    ]
