# Generated by Django 3.1.7 on 2021-03-03 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_auto_20210303_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='audio_path',
        ),
        migrations.AddField(
            model_name='word',
            name='audio',
            field=models.FileField(default=None, max_length=128, storage='static/words_records', upload_to='audio'),
        ),
    ]
