# Generated by Django 3.1.7 on 2021-03-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_auto_20210303_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='audio',
        ),
        migrations.AddField(
            model_name='word',
            name='audio_path',
            field=models.FilePathField(default=None, max_length=512),
        ),
    ]
