# Generated by Django 3.1.7 on 2021-03-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0005_auto_20210303_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='file',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
