# Generated by Django 3.1.7 on 2021-03-12 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_word_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='file',
        ),
    ]
